# Generated by Django 2.1.7 on 2019-03-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='towersite.Image'),
        ),
    ]
