# Generated by Django 2.1.7 on 2019-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towersite', '0002_auto_20190323_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
