# Generated by Django 2.1.7 on 2019-03-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towersite', '0003_auto_20190323_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='towersite.Image'),
        ),
    ]
